# 序号	  访问URL	                   location配置	  proxy_pass配置	       后端接收的请求
# 1	    test.com/user/test.html	   /user/	        http://test1/	       /test.html
# 2	    test.com/user/test.html	   /user/	        http://test1	       /user/test.html
# 3	    test.com/user/test.html	   /user	        http://test1	       /user/test.html
# 4	    test.com/user/test.html	   /user	        http://test1/	       //test.html
# 5	    test.com/user/test.html	   /user/	        http://test1/haha/	   /haha/test.html
# 6	    test.com/user/test.html	   /user/	        http://test1/haha	   /hahatest.html

# qiazo.cn
server {
    listen 80;

    server_name qiazo.cn www.qiazo.cn;
    return 301 https://www.qiazo.cn$request_uri;
}

server {
    listen 443 ssl http2;

    server_name qiazo.cn;

    ssl_certificate     /certs/qiazo.cn.pem;
    ssl_certificate_key /certs/qiazo.cn.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4:!DH:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout  5m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    return 301 https://www.qiazo.cn$request_uri;
}

server {
    listen 443 ssl http2;

    server_name www.qiazo.cn;

    ssl_certificate     /certs/qiazo.cn.pem;
    ssl_certificate_key /certs/qiazo.cn.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4:!DH:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout  5m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    add_header Access-Control-Allow-Origin *;

    location / {
        proxy_pass         http://web:3000/;
        proxy_set_header   Accept-Language        zh;
        proxy_set_header   Custom-Real-Source     cn;
        proxy_set_header   Custom-Forwarded-Host  $host;
        proxy_set_header   X-Real-IP              $remote_addr;
        proxy_set_header   X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto      $http_x_forwarded_proto;
    }
}
