name: PR

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/FUNDING.yml'
      - 'LICENSE'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/FUNDING.yml'
      - 'LICENSE'
      - 'README.md'
    branches:
      - main


# Declare default permissions as readonly.
permissions: read-all

jobs:
  web:
    name: Create web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 18
          package-manager-cache: false

      - name: Install Dependencies
        run: |
          npm i -g corepack
          corepack enable
          pnpm install

      - name: Build web
        run: pnpm build
        env:
          GH_REPO_OWNER: ${{ secrets.GH_REPO_OWNER }}
          GH_REPO: ${{ secrets.GH_REPO }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_REF: ${{ github.sha }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          COOKIE_BANNER_ID: ${{ secrets.COOKIE_BANNER_ID }}
          SHOW_PARTICLES: ${{ secrets.SHOW_PARTICLES }}
          WEBSITE_GLOBAL_GRAY: ${{ secrets.WEBSITE_GLOBAL_GRAY }}
